### ISSUE TITLE
Custom route prefix not working

### ISSUE THREAD

**Issue by smillerk2** [boudinov/mvc-5-routing-localization#1]
This is a great routing example but I'm having problems getting this to work when I have specified a custom route prefix at the controller level. 

When I have deep folder levels I can use route prefix such as /admin/dashboard/home. This works:
```
[RoutePrefix("admin/dashboard")]
    public class HomeController : Controller
    {
        [Route("home")]
        public ActionResult Index()
        {
            return View();
        }
    }
```

When I try and change to use a localized route, I receive 404s:

```
[LocalizedRoute("home")]
        public ActionResult Index()
        {
            return View();
        }
    }
```

I've tried different combinations of the URL being passed to LocalizedRoute but I think the RoutePrefix at the controller level is affecting the routing.

Just wondering if your library supports instances where you may have deep folders (more than the standard 2 levels deep) but still wish to localize the route?

**Comment by boudinov** [comment]
RoutePrefix works normally.
Maybe you didn't get it to work in my example because a root(\~) route is defined, which as normal, ignores any prefix: 
[LocalizedRoute("~/invest")]

I tried these:
[RoutePrefix("admin/dashboard")]
[LocalizedRoute("invest")]

And it works as expected. Note that if you use LocalizedRoute, instead of normal Route, you will need to have 'admin' and 'dashboard'  keys in localization resource files too, as they will too get translated.

**Comment by smillerk2** [comment]
Thanks for clarifying.
